### ISSUE TITLE
Doesn't work with iOS 12.5.5

### ISSUE THREAD

**Issue by NguyenASang** [PoomSmart/CCOnOff#1]
Hello, It's me again :)))
I want to disable Bluetooth but it seems your tweak is not working (install log no errors)

### Some details
I jailbreak using Chimera (latest version) | install using Sileo (also latest version). If you want me to provide any information, I will

**Comment by PoomSmart** [comment]
Define "Not working"

**Comment by NguyenASang** [comment]
@PoomSmart 
Oops sorry, I forgot about it 😅
You can see in this video:

https://user-images.githubusercontent.com/87893636/147814820-049f7b44-07ec-4314-a9cc-ae8dee478ca3.mp4

#### It should disable Bluetooth instead of disconnect it for 1 day

**Comment by PoomSmart** [comment]
@NguyenASang Are you sure you haven't disabled the tweak on iCleaner or have it disabled by Choicy or something?

**Comment by NguyenASang** [comment]
@PoomSmart Oh, I will check it ;))

**Comment by NguyenASang** [comment]
My bad ;)))
