### ISSUE TITLE
Error installing tweak - Sileo

### ISSUE THREAD

**Issue by Terup** [PoomSmart/CCOnOff#2]
Hi there,

Maybe I'm doing something wrong, but when trying to install the CC On&Off tweak it appears that Sileo can't find the file: 
![cc onoff error](https://user-images.githubusercontent.com/130181884/230667515-914c2952-7040-44d5-b957-d64496c6afa5.jpg)

Could it be that the link went down?

**Comment by PoomSmart** [comment]
https://twitter.com/poomsmart/status/1640359662007746560?s=46&t=s24X5WUxto9pOL7U2Nos-A
